-- MySQL Script generated by MySQL Workbench
-- Wed Aug 19 12:44:08 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema query
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema query
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `query` DEFAULT CHARACTER SET utf8 ;
USE `query` ;

-- -----------------------------------------------------
-- Table `query`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `query`.`user` (
  `us_id` INT NOT NULL AUTO_INCREMENT,
  `us_username` VARCHAR(45) NOT NULL,
  `us_password` VARCHAR(255) NOT NULL,
  `us_email` VARCHAR(50) NOT NULL,
  `us_role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`us_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `query`.`query`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `query`.`query` (
  `qr_id` INT NOT NULL AUTO_INCREMENT,
  `qr_question` VARCHAR(255) NOT NULL,
  `qr_answer` VARCHAR(255) NOT NULL,
  `qr_status` boolean NOT NULL,
  `qr_answer_status` boolean NOT NULL,
  `qr_us_id` INT NOT NULL,
  UNIQUE INDEX `qr_id_UNIQUE` (`qr_id` ASC) VISIBLE,
  PRIMARY KEY (`qr_id`),
  INDEX `fk_query_user_idx` (`qr_us_id` ASC) VISIBLE,
  CONSTRAINT `fk_query_user`
    FOREIGN KEY (`qr_us_id`)
    REFERENCES `query`.`user` (`us_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

use query;

INSERT INTO `user`(us_username,us_password,us_email,us_role) VALUES ('admin','$2a$10$R/lZJuT9skteNmAku9Y7aeutxbOKstD5xE5bHOf74M2PHZipyt3yK','admin@gmail.com','ADMIN'),('sai','$2a$10$R/lZJuT9skteNmAku9Y7aeutxbOKstD5xE5bHOf74M2PHZipyt3yK','sai@gmail.com','USER');




